site_name: Serendipity - Dev. Guidelines

theme:
  name: material
  features:
    - instant.loading
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.instant
    - navigation.top
    - navigation.footer
    - navigation.path
    # - navigation.expand
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: date
  - awesome-pages

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
  - attr_list
  - md_in_html

extra_css:
  - assets/css/custom.css

nav:
  - Home:
      - Start here: index.md
  - Project Documentation:
      - Product Requirements Document (PRD):
          - Discovery and Ideation — Worksheet: new-project-kit/docs-template/discovery_and_ideation_worksheet_template.md
          - PRD Template: new-project-kit/docs-template/prd_template.md
      - Technical Design Documentation:
          - TDD Template: new-project-kit/docs-template/tdd_template.md
          - TDD Template (with examples): new-project-kit/docs-template/tdd_template_with_examples.md
  - Codebase Reference: index.md


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SerendipityOrg/TradeMan-Dev-Guidelines
